import { LayoutDashboard, ChartBar as BarChart3, FileText, Boxes, Users, Wallet, Shield, Settings, ChevronLeft, ChevronRight, ChevronDown, Bell, Search, Circle as HelpCircle, LogOut, Check, CircleAlert as AlertCircle, Code as Code2, Terminal, Zap, Building2, BookOpen, Copy, RefreshCcw, Building, ArrowDown, ArrowUp, ArrowRight, ArrowLeft, TrendingUp, Clock, Calendar, Info, CreditCard as Edit, Trash2, Plus, Save, Globe, Server, Key, Package, Upload, FileArchive, Download, Eye, EyeOff, ExternalLink, MessageSquare, Send, LayoutGrid as Layout, Layers, HardDrive, ListFilter as Filter, Activity, MoveHorizontal as MoreHorizontal, CreditCard, History, X, Pause, CircleCheck as CheckCircle, Database, Cloud, Link2, Lock } from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Usage: BarChart3,
  Logs: FileText,
  Models: Boxes,
  Members: Users,
  Quota: Wallet,
  Security: Shield,
  Settings: Settings,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Bell,
  Search,
  Help: HelpCircle,
  HelpCircle,
  LogOut,
  Check,
  Alert: AlertCircle,
  AlertCircle,
  Code: Code2,
  Terminal,
  Zap,
  Building: Building2,
  Book: BookOpen,
  Users,
  Shield,
  Boxes,
  BarChart3,
  Wallet,
  Copy,
  Refresh: RefreshCcw,
  BuildingIcon: Building,
  ArrowDown,
  ArrowUp,
  ArrowRight,
  ArrowLeft,
  TrendingUp,
  Clock,
  Calendar,
  Info,
  Edit,
  Trash: Trash2,
  Plus,
  Save,
  Globe,
  Server,
  Key,
  Package,
  Upload,
  FileArchive,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  MessageSquare,
  Send,
  Layout,
  Layers,
  HardDrive,
  Filter,
  Activity,
  MoreHorizontal,
  CreditCard,
  History,
  Close: X,
  X,
  Pause,
  CheckCircle,
  Database,
  Cloud,
  Link2,
  Lock
};